from .config import CELL_SIZE, WINDOW_HEIGHT, WINDOW_WIDTH, SCORE_SURFACE_HEIGHT, SCORE_SURFACE_WIDTH, GAME_SURFACE_HEIGHT, GAME_SURFACE_WIDTH, BUTTON_WIDTH, BUTTON_HEIGHT, BUTTON_MARGIN, GAME_NAME, SIZE, DIFFICALTIES
from .file_paths import SOUNDS_PATH, EAT_SOUND, LAST_SAVE_PATH, RETRO_FONT_PATH, MENU_BG_TRACK, FAIL_SOUND, SWITCH_BUTTON, ENTER_BUTTON, SAVED_THEME_PATH, MAIN_ICON_PATH
from .themes import THEMES
