SIZE = 600

GAME_SURFACE_HEIGHT = SIZE
GAME_SURFACE_WIDTH = SIZE

SCORE_SURFACE_HEIGHT = 48
SCORE_SURFACE_WIDTH = SIZE

BORDER_WIDTH = 4

BUTTON_WIDTH = 180
BUTTON_HEIGHT = 50
BUTTON_MARGIN = BUTTON_HEIGHT + 20

WINDOW_WIDTH = SIZE
WINDOW_HEIGHT = GAME_SURFACE_HEIGHT + SCORE_SURFACE_HEIGHT + BORDER_WIDTH

CELL_SIZE = 20

COMPLEXITY = 5
WALLS_COUNT = 5

GAME_NAME = 'Retro Snake'
